name: "Testing and Documentation"

on:
  push:
    branches:
      - master

jobs:
  testing-and-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6.2.5
          
      - name: Install Dependencies
        shell: bash
        run: npm install --include dev
    
      - name: Build Documentation
        shell: bash
        run: npm run build:docs
      
      - name: Run Tests and Build Reports
        shell: bash
        run: npm run test
      
      - name: Copy Test Reports to Site
        shell: bash
        run: cp ./jest_html_reporters.html ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs